name: AutomaticInventory
main: me.ryanhamshire.AutomaticInventory.AutomaticInventory
authors: [Big_Scary, RoboMWM, AllTheCode, Pugabyte]
version: '${project.version}-${git.commit.id.abbrev}'
api-version: '1.14'
commands:
  debugai:
    description: Debug command for AutomaticInventory.
    usage: /debugai
    permission: automaticinventory.debug
  autosort:
    description: Toggles auto-sorting options.
    usage: /AutoSort
    permission: automaticinventory.sortchests
  depositall:
    description: Deposits your non-hotbar inventory into any nearby chests containing matching items.
    usage: /DepositAll
    aliases: [da, dumpitems, dumploot, depositloot]
    permission: automaticinventory.depositall
permissions:
  automaticinventory.admin.*:
    description: Grants all administrative privileges.
    children:
      automaticinventory.debugai: true
  automaticinventory.user.*:
    description: Grants all user privileges.
    children:
      automaticinventory.sortinventory: true
      automaticinventory.sortchests: true
      automaticinventory.refillstacks: true
      automaticinventory.quickdeposit: true
      automaticinventory.depositall: true
  automaticinventory.debugai:
    description: Grants permission to use /DebugAI.
    default: op
  automaticinventory.sortinventory:
    description: Grants permission to auto-sort personal inventory.
    default: op
  automaticinventory.sortchests:
    description: Grants permission to auto-sort chest content.
    default: op
  automaticinventory.refillstacks:
    description: Grants permission to auto-refill depleted hotbar stacks.
    default: op
  automaticinventory.quickdeposit:
    description: Grants permission to auto-deposit matching items into a chest with shift-right-click.
    default: op
  automaticinventory.depositall:
    description: Grants permission to use /DepositAll.
    default: op
  automaticinventory.autocraft:
    description: Grants permission to auto-craft.
    default: op
